---
title: "aRchaic damage profile analysis by pathtpx"
author: "Kushal K Dey"
date: "7/5/2017"
output: html_document
---

We now apply **pathtpx** on ancient DNA mismatch patterns data. 

We form two groups - a damage profile class which includes C->T mutations occurring at the ends of the reads, and all other mismatches being classified as non-damage profile.

```{r}
library(pathtpx)
set.seed(100)
library(maptpx)
library(slam)
```

```{r}
moderns_data <- get(load("../../ancient-damage/data/moderns_lite/moderns_lite.rda"))
sherpa_data <- get(load("../../ancient-damage/data/Sherpa_data/Sherpa_data.rda"))

pooled_data <- rbind(moderns_data, sherpa_data)

features <- colnames(pooled_data)
muts <- substring(features, 2, 5)
pos <- sapply(features, function(x) return(as.numeric(tail(strsplit(x, "_")[[1]],1))))

damage_index <- names(which(muts=="C->T" & pos < 10))

pathway_names <- list()
pathway_names[[1]] <- damage_index
pathway_names[[2]] <- setdiff(colnames(pooled_data), pathway_names[[1]])

```

```{r}
topic_clus <- pathtopics(pooled_data, pathways = pathway_names, tol = 0.01, ord=FALSE)
```

```{r}
theta <- topic_clus$theta
omega <- topic_clus$omega
```

```{r fig.height=10, fig.width=6}
labs <- c(rep("moderns", 50), rep("sherpa", 5))

annotation <- data.frame(
  sample_id = paste0("X", c(1:NROW(omega))),
  tissue_label = factor(labs,
                        levels = unique(labs) ) )


rownames(omega) <- annotation$sample_id;


CountClust::StructureGGplot(omega = omega,
                            annotation = annotation,
                            palette = RColorBrewer::brewer.pal(8, "Accent"),
                            yaxis_label = "aRchaic GoM",
                            order_sample = TRUE,
                            axis_tick = list(axis_ticks_length = .1,
                                             axis_ticks_lwd_y = .1,
                                             axis_ticks_lwd_x = .1,
                                             axis_label_size = 7,
                                             axis_label_face = "bold"))

```


```{r}
plot(theta[,1], pch=20)
sort(theta[,1], decreasing = TRUE)[1:10]
```

```{r}
plot(theta[,2], pch=20)
sort(theta[,2], decreasing = TRUE)[1:10]
```

```{r}
topic_clus_2 <- maptpx::topics(pooled_data, K=2, tol = 1)
```

```{r}
omega2 <- topic_clus_2$omega
theta2 <- topic_clus_2$theta
```

```{r fig.height=10, fig.width=6}
labs <- c(rep("moderns", 50), rep("sherpa", 5))

annotation <- data.frame(
  sample_id = paste0("X", c(1:NROW(omega2))),
  tissue_label = factor(labs,
                        levels = unique(labs) ) )


rownames(omega2) <- annotation$sample_id;


CountClust::StructureGGplot(omega = omega2,
                            annotation = annotation,
                            palette = RColorBrewer::brewer.pal(8, "Accent"),
                            yaxis_label = "aRchaic GoM",
                            order_sample = TRUE,
                            axis_tick = list(axis_ticks_length = .1,
                                             axis_ticks_lwd_y = .1,
                                             axis_ticks_lwd_x = .1,
                                             axis_label_size = 7,
                                             axis_label_face = "bold"))

```

```{r}
plot(theta2[,1], pch=20)
sort(theta2[,1], decreasing = TRUE)[1:10]
```


```{r}
plot(theta2[,2], pch=20)
sort(theta2[,2], decreasing = TRUE)[1:10]
```

